apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.internalVolume }}
  namespace: {{ .Values.namespace }}
  annotations:
    volume.beta.kubernetes.io/storage-class: {{ .Values.internalVolumeStorageClass }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.internalVolumeSize }}
